# Numpy

In [51]:
import numpy as np

arr : np.ndarray = np.array(1000)

display(arr)
display(f"Shape of the array {arr.shape}")
display(f"Size of the array {arr.size}")
display(f"Number of Dimensions {arr.ndim}")
display(f"Data type of the array {arr.dtype}")
display(f"No. of items in the array {arr.itemsize}")

array(1000)

'Shape of the array ()'

'Size of the array 1'

'Number of Dimensions 0'

'Data type of the array int32'

'No. of items in the array 4'

## Vectors

In [52]:
arr : np.ndarray = np.array([1, 2, 3, 4, 5,12,8,6])

# Perform mathematical operations on arrays
arr2 : np.ndarray = arr + 5  # Add 5 to each element of the array 'arr'
arr3 : np.ndarray = np.sin(arr) # Calculate the sine of each element of the array 'arr'

# Perform array operations
arr4 : np.ndarray = np.concatenate((arr, arr2))  # Concatenate 'arr' and 'arr2' to create a new array

# Perform array computations
mean = display(np.mean(arr))  # Calculate the mean (average) of the elements in 'arr'
max_value = display(np.max(arr))  # Find the maximum value in 'arr'


5.125

12


### Explanation

In the first code snippet, we import the NumPy library as `np` and create a NumPy array called `arr` with the elements `[1, 2, 3, 4, 5]`. We then perform several operations on this array:

1. `arr2` is created by adding 5 to each element of `arr`.
2. `arr3` is created by calculating the sine of each element in `arr`.
3. `arr4` is created by concatenating `arr` and `arr2`.

Additionally, we perform some array computations:

- We calculate the mean (average) of the elements in `arr` and store it in the variable `mean`.
- We find the maximum value in `arr` and store it in the variable `max_value`.



In [53]:
import numpy as np

arr: np.ndarray = np.array([1, 2, 3, 4, 5])
print(arr)

display(arr)  # prints the array
display(arr.shape)  # prints the shape of the array
display(arr.dtype)  # prints the datatype of the array
display(arr.ndim)  # prints the number of dimensions of the array
display(arr.size)  # prints the number of elements in the array
display(arr.itemsize)  # prints the size of the array



[1 2 3 4 5]


array([1, 2, 3, 4, 5])

(5,)

dtype('int32')

1

5

4

### Explanation

In the second code snippet, we import the NumPy library and create a NumPy array called `arr` with the elements `[1, 2, 3, 4, 5]`. This time, we use static typing to specify the type of `arr` as `np.ndarray`.

We then display various properties of the array using the `display` function:

- `arr` is printed, showing the array itself.
- `arr.shape` is printed, displaying the shape of the array.
- `arr.dtype` is printed, showing the data type of the array.
- `arr.ndim` is printed, indicating the number of dimensions of the array.
- `arr.size` is printed, revealing the number of elements in the array.
- `arr.itemsize` is printed, indicating the item size of the array.

Static typing is applied to the `arr` variable by specifying its type as `np.ndarray` to improve code clarity and maintainability.


In [54]:
array : np.ndarray = np.ndarray

## Vector Matrix

In [55]:
array : np.ndarray = np.array(
    [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

display(f"Object  {array}")
display(f"Shape of the object:  {array.shape}")
display(f"Size of the array {array.size}")
display(f"Size of the array {array.itemsize}")
display(f"Number of dimensions {array.ndim}")

'Object  [[1 2 3]\n [4 5 6]\n [7 8 9]]'

'Shape of the object:  (3, 3)'

'Size of the array 9'

'Size of the array 4'

'Number of dimensions 2'

## Numpy with NDarray typing Support

In [56]:
%%time
# To check the time status of program execution. 

from nptyping import NDArray, Shape,UInt64

data : NDArray[Shape['10'],UInt64] = np.arange(1,11)

display(data)
data + 5 # Adding 5 to each element of the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

CPU times: total: 0 ns
Wall time: 5.87 ms


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
# Doing the same thing with python list
list1 : list[int] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[i+5 for i in list1]

# Numpy makes it easy like you are performing an operation between two operands.

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

## numpy advanced operations vs list operations

In [58]:
data : list[int] = list(range(1,21))

print(data)
print(data[5:11])
data[5:11] =100

# This operation cannot be performed in python list.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [ ]:
array : NDArray[Shape['20'],Any] = np.arange(1,21)

print(array)
print(array[5:11])
array[5:11] = 100
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[  1   2   3   4   5 100 100 100 100 100 100  12  13  14  15  16  17  18
  19  20]


## Boolean Search numpy

In [ ]:
state_bank : NDArray[Shape['10'],UInt64] = np.array([1,7,8,10])

state_bank % 2 ==0

array([False, False,  True,  True])

In [ ]:
state_bank : NDArray[Shape['10'],UInt64] = np.array([1,7,8,10])

state_bank[state_bank % 2 ==0]

array([ 8, 10])

## Numpy 1D functions

In [ ]:
from nptyping import Bool


state_bank : NDArray[Shape['10'],UInt64] = np.array([1,2,5,7,10])

select : NDArray[Shape['10'],Bool] = np.array([True, False, False,True,False])

state_bank[select]

array([1, 7])

In [ ]:
state_bank :NDArray[Shape['10'],UInt64] = np.array([1,2,3,4,8,12,7,16])

state_bank[state_bank % 2 ==0]

array([ 2,  4,  8, 12, 16])

## Random number Numpy

In [ ]:
state_bank : NDArray[Shape['10'],UInt64] = np.array([12,28,46,77,53])

ubl_bank : NDArray[Shape['10'],UInt64] = np.random.randint(1,100,20)

display(state_bank)
display(ubl_bank)

array([12, 28, 46, 77, 53])

array([56, 35, 76, 31, 24, 62, 85, 92, 15, 54, 50, 48, 25, 40, 78, 28, 41,
       25, 38, 59])

In [ ]:
display(state_bank)
display(ubl_bank)

#        5 items       search 20 items
np.in1d(state_bank,ubl_bank) 

array([12, 28, 46, 77, 53])

array([56, 35, 76, 31, 24, 62, 85, 92, 15, 54, 50, 48, 25, 40, 78, 28, 41,
       25, 38, 59])

array([False,  True, False, False, False])

#### Code Explanation
Test whether each element of a 1-D array is also present in a second array.

Returns a boolean array the same length as ar1 that is True where an element of ar1 is in ar2 and False otherwise.

In [ ]:
np.intersect1d(state_bank,ubl_bank)

# Find the intersection of two arrays.

# Return the sorted, unique values that are in both of the input arrays.

array([28])

In [ ]:
arr1 : NDArray[Shape["5"],UInt64] = np.array([1,3,4,5,120])
arr2 : NDArray[Shape["5"],UInt64] = np.array([6,3,2,5,100])

display(arr1)
display(arr2)
np.where(arr1 > arr2,arr1,arr2)

array([  1,   3,   4,   5, 120])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 120])

#### Code Explanation

`np.where` compares the values of `arr1` and `arr2` and selects the maximum values element-wise.

## Create Numpy Arrays 2D arrays

In [59]:
from typing import Any
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


### Explanation

`NDArray[Shape["Size, Size"], Any]`

`["Size", "Size]` means that it can have any type of size. We are not explicitly describing this.

**Alternatively**

We could have `NDArray[Shape["*", "*"], Any]`

we can use a `*` to tell that it has any size.

In [60]:
a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [61]:
np.who()

Name            Shape            Bytes            Type

__              10               40               int32
___             5                20               int32
arr             5                20               int32
arr2            8                32               int32
arr3            8                64               float64
arr4            16               64               int32
array           3 x 3            36               int32
_6              10               40               int32
state_bank      5                20               int32
select          5                5                bool
_16             2                8                int32
_18             2                8                int32
_20             2                8                int32
_21             2                8                int32
_22             2                8                int32
_23             2                8                int32
_24             8                8             

## np.who()

Print the NumPy arrays in the given dictionary.

If there is no dictionary passed in or vardict is None then returns NumPy arrays in the globals() dictionary (all NumPy arrays in the namespace).

## Any Dimensional array

In [62]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a)
a : NDArray[Shape["Size"],Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [63]:
a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(a)
a : NDArray[Shape["Size, Size"],Any] = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [65]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)
print('=======')
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [66]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])